name: Criar pipeline completo GitHub Pages

on:
  push:                     # Quando ocorrer um push 
    
permissions:
  contents: write

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .            # publica todo o conteúdo da raiz
          publish_branch: gh-teste  # garante que publique na branch gh-pages
